[build]
  base = "fisherman"
  command = "npm run build"
  publish = "fisherman/dist"
  functions = "fisherman/netlify/functions"

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/gas-proxy"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/gas-proxy"
  status = 200
